:version: 1.0.0

= Jasmine Gradle Plugin

This Gradle plugin allows you to run Jasmine tests using Karma from your build.

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
buildscript {
    dependencies {
        classpath "com.craigburke.gradle:jasmine:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'com.craigburke.jasmine'
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| jasmineRun | Runs your jasmine tests

| jasmineWatch | Runs your jasmine tests in watch mode

| jasmineClean | Removes generated karma config file

|===

== Configuration

You can use the same properties you'd set in your http://bower.io/docs/creating-packages/#bowerjson[bower.json file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
buildscript {
    dependencies {
        classpath "com.craigburke.gradle:jasmine:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'com.craigburke.jasmine'

jasmine {
    basePath = '' <1>
    files = [ // <2>
        'libs/bower/angular/angular.js',
        'libs/bower/**/*.js',
        '**/*.module.js',
        '**/!(*.spec).js',
        '**/*.spec.js'
    ]
}
----
<1> Optional base path for relative path options (like files).
<2> List of files for Karma to load

NOTE: if *basePath* is not set, it defaults to `src/assets` or `grails-app/assets` if the Grails plugin is applied.

=== Optional properties

In addition to the properties listed above, you can also include set other Karma properties through the additional map.
 
[source,gradle,subs='attributes']
----
jasmine {
    additional = [ // <1>
        colors: true
    ]
}
----
<2> *additional* is a map that allows additional properties to be added to Karma's configuration.